<?php

namespace App\Modules\Order\Resources;

use Common\Http\Resources\AbstractResource;
use Illuminate\Support\Collection;

class OrderNoteResource extends AbstractResource
{
    /**
     * @param Collection $resource
     */
    public function __construct(Collection $resource)
    {
        parent::__construct($resource);
    }

    /**
     * @param $request
     * @return array|\Illuminate\Contracts\Support\Arrayable|\JsonSerializable
     */
    public function toArray($request)
    {
        return [
            'store_id' => $this->store_id,
            'order_id' => $this->order_id,
            'customer_id' => $this->customer_id,
            'type' => $this->type,
            'note' => $this->note,
            'created_by' => $this->created_by,
            'updated_by' => $this->updated_by,
        ]; // TODO: Change the autogenerated stub
    }
}