<?php

namespace App\Modules\Campaign\Resources;

use Common\Http\Resources\AbstractResource;
use Common\Models\AbstractModel;
use Illuminate\Http\Resources\MergeValue;
use OmSdk\Modules\Campaign\Models\Campaign;
use Symfony\Component\Translation\Exception\InvalidResourceException;

class CampaignResource extends AbstractResource
{
    /**
     * @var Campaign $resource
     */
    public $resource;

    /**
     * @param $request
     * @return array|\Illuminate\Contracts\Support\Arrayable|\JsonSerializable
     */
    public function toArray($request)
    {
        if (!$this->resource instanceof AbstractModel) {
            throw new InvalidResourceException();
        }

        return [
            'id' => $this->resource->id,
            'store_id' => $this->resource->store_id,
            'title' => $this->resource->title,
            'advertisement_id' => $this->resource->advertisement_id,
            'channel_id' => $this->resource->channel_id,
            'sub_channel_id' => $this->resource->sub_channel_id,
            'product_catalog_id' => $this->resource->product_catalog_id,
            'assigned_user_id' => $this->resource->assigned_user_id,
            'link_token' => $this->resource->link_token,
            'created_by' => $this->resource->created_by,
            'updated_by' => $this->resource->updated_by,
            'payment_account_id' => $this->resource->payment_account_id,
            'estimated_amount' => $this->resource->estimated_amount,
            'estimated_data' => $this->resource->estimated_data,
            'estimated_revenue' => $this->resource->estimated_revenue,
            'actual_data' => $this->resource->actual_data,
            'actual_amount' => $this->resource->actual_amount,
            'actual_revenue' => $this->resource->actual_revenue,
            'reference_source' => $this->resource->reference_source,
            'start_at' => $this->resource->start_at,
            'end_at' => $this->resource->end_at,
            'is_active' => $this->resource->is_active,
            'code' => $this->resource->code,
            new MergeValue([
                'channel' => $this->resource->channel,
                'sub_channel' => $this->resource->subChannel,
                'user_assign' => $this->resource->userAssign,
                'payment_accounts' => $this->resource->paymentAccounts,
                'product_catalog' => $this->resource->producCatalog
            ])
        ]; // TODO: Change the autogenerated stub
    }

}