<?php

namespace App\Modules\Payment\Resources;

use Common\Http\Resources\AbstractResource;
use Common\Models\AbstractModel;
use Symfony\Component\Translation\Exception\InvalidResourceException;

class PaymentResources extends AbstractResource
{
    /**
     * @param $request
     * @return array
     */
    public function toArray($request)
    {
        if (!$this->resource instanceof AbstractModel) {
            throw new InvalidResourceException();
        } // TODO: Change the autogenerated stub

        return [
            'id' => $this->id,
            'store_id' => $this->store_id,
            'bank_name' => $this->bank_name,
            'card_type' => $this->card_type,
            'card_number' => $this->card_number,
            'account_number' => $this->account_number,
            'card_owner' => $this->card_owner,
            'created_by' => $this->created_by,
            'updated_by' => $this->updated_by,
            'is_active' => $this->is_active,
            'user' => $this->user
        ];
    }
}