<?php

namespace App\Modules\MissionScript\Requests;

use Common\Http\Requests\AbstractRequest;

class MissionScriptRequest extends AbstractRequest
{
    /**
     * Get custom attributes for validator errors.
     *
     * @return array
     */
    public function attributes()
    {
        return [] ;
    }

    /**
     * @return array
     */
    public function rules()
    {
        return [];
    }
    public function messages()
    {
        return []; // TODO: Change the autogenerated stub
    }
}